spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: contact-postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ihavebroughtpeacefreedomjusticeandsecuritytomynewempire